import type { SaasIdea } from "./types";

// ─────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────

function slug(idea: SaasIdea): string {
  return idea.idea_name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
}

export function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

function arr(items: string[]): string {
  return items.length ? items.map((i) => `  • ${i}`).join("\n") : "  • —";
}

// ─────────────────────────────────────────────
// Single — Text
// ─────────────────────────────────────────────

export function ideaToText(idea: SaasIdea, subreddit: string): string {
  return [
    `╔══════════════════════════════════════════════╗`,
    `  VALIDATED SAAS IDEA — r/${subreddit}`,
    `╚══════════════════════════════════════════════╝`,
    ``,
    `  ${idea.idea_name}`,
    `  Score: ${idea.score}/10   Verdict: ${idea.verdict}   Demand: ${idea.demand_level}`,
    ``,
    `PROBLEM`,
    `  ${idea.problem}`,
    ``,
    `OPPORTUNITY`,
    `  ${idea.opportunity}`,
    ``,
    `USER COMPLAINTS`,
    arr(idea.user_complaints),
    ``,
    `EXISTING SOLUTIONS`,
    arr(idea.existing_solutions),
    ``,
    `SIMILAR COMPETITORS`,
    arr(idea.similar_competitors),
    ``,
    `MONETIZATION`,
    `  ${idea.monetization_model}`,
    ``,
    `PRICING HINT`,
    `  ${idea.pricing_hint}`,
    ``,
    `REVENUE POTENTIAL`,
    `  ${idea.revenue_potential}`,
    ``,
    `GO TO MARKET`,
    `  ${idea.go_to_market}`,
    ``,
    `SOURCE THREADS`,
    ...(idea.source_threads.length
      ? idea.source_threads.map((t) => `  • ${t.title}\n    ${t.thread_url}`)
      : ["  • —"]),
    ``,
    `Generated by Validly — https://validly.dev`,
  ].join("\n");
}

// ─────────────────────────────────────────────
// Single — Markdown
// ─────────────────────────────────────────────

export function ideaToMarkdown(idea: SaasIdea, subreddit: string): string {
  const threads = idea.source_threads.length
    ? idea.source_threads.map((t) => `- [${t.title}](${t.thread_url})`).join("\n")
    : "- —";

  return [
    `# ${idea.idea_name}`,
    ``,
    `> **Source:** r/${subreddit} · **Score:** ${idea.score}/10 · **Verdict:** ${idea.verdict} · **Demand:** ${idea.demand_level}`,
    ``,
    `## Problem`,
    ``,
    idea.problem,
    ``,
    `## Opportunity`,
    ``,
    idea.opportunity,
    ``,
    `## User Complaints`,
    ``,
    ...idea.user_complaints.map((c) => `- ${c}`),
    ``,
    `## Existing Solutions`,
    ``,
    ...idea.existing_solutions.map((s) => `- ${s}`),
    ``,
    `## Similar Competitors`,
    ``,
    ...idea.similar_competitors.map((c) => `- ${c}`),
    ``,
    `## Monetization`,
    ``,
    idea.monetization_model,
    ``,
    `## Pricing Hint`,
    ``,
    idea.pricing_hint,
    ``,
    `## Revenue Potential`,
    ``,
    idea.revenue_potential,
    ``,
    `## Go to Market`,
    ``,
    idea.go_to_market,
    ``,
    `## Source Threads`,
    ``,
    threads,
    ``,
    `---`,
    `*Generated by [Validly](https://validly.dev)*`,
  ].join("\n");
}

// ─────────────────────────────────────────────
// Single — JSON
// ─────────────────────────────────────────────

export function ideaToJson(idea: SaasIdea, subreddit: string): string {
  return JSON.stringify({ subreddit, ...idea }, null, 2);
}

// ─────────────────────────────────────────────
// Single — Image (Canvas 2D, zero dependencies)
// ─────────────────────────────────────────────

const CARD_W = 900;
const PAD = 48;
const LINE_HEIGHT = 26;
const SECTION_GAP = 22;

function scoreColor(score: number): string {
  if (score >= 8) return "#059669"; // emerald
  if (score >= 5) return "#d97706"; // amber
  return "#e11d48"; // rose
}

function wrapText(
  ctx: CanvasRenderingContext2D,
  text: string,
  x: number,
  y: number,
  maxWidth: number,
): number {
  const words = text.split(" ");
  let line = "";
  let curY = y;

  for (const word of words) {
    const test = line ? `${line} ${word}` : word;
    if (ctx.measureText(test).width > maxWidth && line) {
      ctx.fillText(line, x, curY);
      curY += LINE_HEIGHT;
      line = word;
    } else {
      line = test;
    }
  }
  if (line) ctx.fillText(line, x, curY);
  return curY + LINE_HEIGHT;
}

function drawSection(
  ctx: CanvasRenderingContext2D,
  label: string,
  value: string | string[],
  x: number,
  y: number,
  maxWidth: number,
): number {
  // Label
  ctx.font = "600 11px 'Inter', ui-sans-serif, system-ui, sans-serif";
  ctx.fillStyle = "#64748b";
  ctx.letterSpacing = "0.12em";
  ctx.fillText(label.toUpperCase(), x, y);
  y += 18;

  ctx.font = "400 14px 'Inter', ui-sans-serif, system-ui, sans-serif";
  ctx.fillStyle = "#1e293b";
  ctx.letterSpacing = "0";

  if (Array.isArray(value)) {
    for (const item of value.filter(Boolean)) {
      ctx.fillText("•", x, y);
      y = wrapText(ctx, item, x + 14, y, maxWidth - 14);
    }
  } else {
    y = wrapText(ctx, value, x, y, maxWidth);
  }

  return y + SECTION_GAP;
}

export async function ideaToPng(idea: SaasIdea, subreddit: string): Promise<Blob> {
  // First pass: measure height
  const probe = document.createElement("canvas");
  const pctx = probe.getContext("2d")!;
  const contentWidth = CARD_W - PAD * 2;
  let estimatedY = PAD + 100 + SECTION_GAP * 10;
  // rough estimate — real height computed below via draw pass
  const fields: Array<[string, string | string[]]> = [
    ["Problem", idea.problem],
    ["Opportunity", idea.opportunity],
    ["User Complaints", idea.user_complaints],
    ["Existing Solutions", idea.existing_solutions],
    ["Similar Competitors", idea.similar_competitors],
    ["Monetization", idea.monetization_model],
    ["Pricing Hint", idea.pricing_hint],
    ["Revenue Potential", idea.revenue_potential],
    ["Go to Market", idea.go_to_market],
  ];

  // Compute height with a dry-run
  const measureCanvas = document.createElement("canvas");
  measureCanvas.width = CARD_W;
  measureCanvas.height = 4000;
  const mctx = measureCanvas.getContext("2d")!;
  let mY = PAD + 110;
  for (const [label, value] of fields) {
    mY = drawSection(mctx, label, value as string | string[], PAD, mY, contentWidth);
  }
  // source threads
  if (idea.source_threads.length) {
    mctx.font = "600 11px 'Inter', ui-sans-serif, system-ui, sans-serif";
    mY += 18;
    for (const t of idea.source_threads) {
      mctx.font = "400 13px 'Inter', ui-sans-serif, system-ui, sans-serif";
      mY = wrapText(mctx, `• ${t.title}`, PAD + 14, mY, contentWidth - 14);
    }
  }
  const CANVAS_H = mY + PAD + 50;

  // Real canvas
  const canvas = document.createElement("canvas");
  canvas.width = CARD_W;
  canvas.height = CANVAS_H;
  const ctx = canvas.getContext("2d")!;

  // Background
  ctx.fillStyle = "#f8fafc";
  ctx.fillRect(0, 0, CARD_W, CANVAS_H);

  // Card body
  const radius = 28;
  ctx.fillStyle = "#ffffff";
  ctx.beginPath();
  ctx.roundRect(PAD / 2, PAD / 2, CARD_W - PAD, CANVAS_H - PAD, radius);
  ctx.fill();

  // Border
  ctx.strokeStyle = "#e2e8f0";
  ctx.lineWidth = 1.5;
  ctx.beginPath();
  ctx.roundRect(PAD / 2, PAD / 2, CARD_W - PAD, CANVAS_H - PAD, radius);
  ctx.stroke();

  // Top accent bar
  const grad = ctx.createLinearGradient(PAD / 2, 0, CARD_W - PAD / 2, 0);
  grad.addColorStop(0, "#f97316");
  grad.addColorStop(0.5, "#fbbf24");
  grad.addColorStop(1, "#38bdf8");
  ctx.fillStyle = grad;
  ctx.beginPath();
  ctx.roundRect(PAD / 2, PAD / 2, CARD_W - PAD, 4, [radius, radius, 0, 0]);
  ctx.fill();

  let y = PAD + 30;
  const x = PAD + 12;
  const cw = CARD_W - PAD * 2 - 24;

  // Subreddit tag
  ctx.font = "600 11px 'Inter', ui-sans-serif, system-ui, sans-serif";
  ctx.fillStyle = "#94a3b8";
  ctx.letterSpacing = "0.16em";
  ctx.fillText(`r/${subreddit.toUpperCase()}  ·  VALIDLY`, x, y);
  y += 28;

  // Idea name
  ctx.font = "700 28px 'Inter', ui-sans-serif, system-ui, sans-serif";
  ctx.fillStyle = "#0f172a";
  ctx.letterSpacing = "-0.02em";
  y = wrapText(ctx, idea.idea_name, x, y, cw - 140);

  // Score badge
  const badgeColor = scoreColor(idea.score);
  const badgeX = CARD_W - PAD - 12 - 120;
  const badgeY = PAD + 38;
  ctx.fillStyle = badgeColor + "18";
  ctx.beginPath();
  ctx.roundRect(badgeX, badgeY, 120, 38, 20);
  ctx.fill();
  ctx.strokeStyle = badgeColor + "55";
  ctx.lineWidth = 1.5;
  ctx.beginPath();
  ctx.roundRect(badgeX, badgeY, 120, 38, 20);
  ctx.stroke();
  ctx.font = "700 14px 'Inter', ui-sans-serif, system-ui, sans-serif";
  ctx.fillStyle = badgeColor;
  ctx.letterSpacing = "0";
  ctx.textAlign = "center";
  ctx.fillText(`Score ${idea.score}/10`, badgeX + 60, badgeY + 24);
  ctx.textAlign = "left";

  // Verdict + demand pills row
  ctx.font = "600 12px 'Inter', ui-sans-serif, system-ui, sans-serif";
  ctx.fillStyle = "#475569";
  ctx.fillText(`${idea.verdict} Signal  ·  Demand: ${idea.demand_level}`, x, y);
  y += SECTION_GAP + 8;

  // Divider
  ctx.strokeStyle = "#f1f5f9";
  ctx.lineWidth = 1;
  ctx.beginPath();
  ctx.moveTo(x, y);
  ctx.lineTo(CARD_W - x, y);
  ctx.stroke();
  y += SECTION_GAP;

  // Fields
  for (const [label, value] of fields) {
    y = drawSection(ctx, label, value as string | string[], x, y, cw);
  }

  // Source threads
  if (idea.source_threads.length) {
    ctx.font = "600 11px 'Inter', ui-sans-serif, system-ui, sans-serif";
    ctx.fillStyle = "#64748b";
    ctx.letterSpacing = "0.12em";
    ctx.fillText("SOURCE THREADS", x, y);
    y += 18;
    ctx.letterSpacing = "0";
    for (const t of idea.source_threads) {
      ctx.font = "400 13px 'Inter', ui-sans-serif, system-ui, sans-serif";
      ctx.fillStyle = "#334155";
      y = wrapText(ctx, `• ${t.title}`, x + 14, y, cw - 14);
    }
    y += SECTION_GAP;
  }

  // Footer
  ctx.font = "400 12px 'Inter', ui-sans-serif, system-ui, sans-serif";
  ctx.fillStyle = "#94a3b8";
  ctx.fillText("Generated by Validly", x, y + 8);

  return new Promise((resolve) => {
    canvas.toBlob(
      (blob) => resolve(blob ?? new Blob([], { type: "image/png" })),
      "image/png",
    );
  });
}

// ─────────────────────────────────────────────
// Bulk — all ideas
// ─────────────────────────────────────────────

export function ideasToText(ideas: SaasIdea[], subreddit: string): string {
  const separator = `\n${"═".repeat(56)}\n\n`;
  return ideas.map((idea) => ideaToText(idea, subreddit)).join(separator);
}

export function ideasToMarkdown(ideas: SaasIdea[], subreddit: string): string {
  return [
    `# Validated SaaS Ideas — r/${subreddit}`,
    ``,
    `> ${ideas.length} ideas generated by Validly`,
    ``,
    ...ideas.map((idea, i) => [`## ${i + 1}. ${idea.idea_name}`, ``, ideaToMarkdown(idea, subreddit)].join("\n")),
  ].join("\n");
}

export function ideasToJson(ideas: SaasIdea[], subreddit: string): string {
  return JSON.stringify({ subreddit, ideas }, null, 2);
}

export async function ideasToPng(ideas: SaasIdea[], subreddit: string): Promise<Blob[]> {
  const blobs: Blob[] = [];
  for (const idea of ideas) {
    blobs.push(await ideaToPng(idea, subreddit));
  }
  return blobs;
}

// ─────────────────────────────────────────────
// Download helpers
// ─────────────────────────────────────────────

export type ExportFormat = "text" | "markdown" | "json" | "image";

export async function exportIdea(
  idea: SaasIdea,
  subreddit: string,
  format: ExportFormat,
): Promise<void> {
  const name = slug(idea);
  const sub = subreddit.toLowerCase();

  if (format === "text") {
    downloadBlob(new Blob([ideaToText(idea, subreddit)], { type: "text/plain" }), `${name}-${sub}.txt`);
  } else if (format === "markdown") {
    downloadBlob(new Blob([ideaToMarkdown(idea, subreddit)], { type: "text/markdown" }), `${name}-${sub}.md`);
  } else if (format === "json") {
    downloadBlob(new Blob([ideaToJson(idea, subreddit)], { type: "application/json" }), `${name}-${sub}.json`);
  } else {
    const blob = await ideaToPng(idea, subreddit);
    downloadBlob(blob, `${name}-${sub}.png`);
  }
}

export async function exportAllIdeas(
  ideas: SaasIdea[],
  subreddit: string,
  format: ExportFormat,
): Promise<void> {
  const sub = subreddit.toLowerCase();
  const ts = new Date().toISOString().slice(0, 10);
  const base = `validly-${sub}-${ts}`;

  if (format === "text") {
    downloadBlob(new Blob([ideasToText(ideas, subreddit)], { type: "text/plain" }), `${base}.txt`);
  } else if (format === "markdown") {
    downloadBlob(new Blob([ideasToMarkdown(ideas, subreddit)], { type: "text/markdown" }), `${base}.md`);
  } else if (format === "json") {
    downloadBlob(new Blob([ideasToJson(ideas, subreddit)], { type: "application/json" }), `${base}.json`);
  } else {
    // Bulk image: download each card individually
    const blobs = await ideasToPng(ideas, subreddit);
    blobs.forEach((blob, i) => {
      const s = slug(ideas[i]);
      downloadBlob(blob, `${base}-${i + 1}-${s}.png`);
    });
  }
}
